services:
  app:
    build: .
    container_name: app-web
    ports:
      - "8080:80"
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      APP_SECRET: change_me
      DATABASE_URL: "mysql://symfony:symfony@db:3306/bd_droits_juridiques?serverVersion=8.0&charset=utf8mb4"
      MAILER_DSN: "null://null"
      COMPOSER_MEMORY_LIMIT: "-1"
      COMPOSER_ALLOW_SUPERUSER: "1"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    command: >
      bash -lc "
      if [ ! -f vendor/autoload.php ]; then
        composer install --no-dev --prefer-dist --no-interaction --no-progress || exit 1;
      fi
      && php bin/console cache:clear || true
      && apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: app-db
    restart: always
    environment:
      MYSQL_DATABASE: bd_droits_juridiques
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
