framework:
  mailer:
    dsn: '%env(MAILER_DSN)%'
    envelope:
      sender: '%env(APP_FROM_EMAIL)%'   # adresse utilisée pour l’envoi SMTP
    headers:
      From: '%env(APP_FROM_NAME)% <%env(APP_FROM_EMAIL)%>'
