# config/services.yaml
parameters:
  app.from_email: '%env(APP_FROM_EMAIL)%'
  app.from_name:  '%env(APP_FROM_NAME)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $fromEmail: '%app.from_email%'
      string $fromName:  '%app.from_name%'

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Security\EmailVerifier:
    arguments:
      $fromEmail: '%app.from_email%'
      $fromName:  '%app.from_name%'
